### ISSUE TITLE
Video Retrieval

### ISSUE THREAD

**Issue by lucaro** [xiaobai1217/Awesome-Video-Datasets#1]
Hey, this is a great list, good job!

I'd have one comment though: under Video Retrieval you list TRECVID, which is a campaign and not a dataset. TRECVID has several tasks, each using different datasets. Not all of those are publicly available, but some of the larger ones are. The two most relevant here are IACC and V3C. IACC (Internet Archive Creative Commons) is a collection of video from the internet archive which has been used in TRECVID for several years and has in the process accumulated many types of annotations. The V3C (Vimeo Creative Commons Collection) is the newer general purpose video dataset, composed of creative commons content from vimeo and designed to be representative of web video in general. Both of these datasets have papers and resources associated with them. The main ones are https://dl.acm.org/doi/abs/10.1145/1631135.1631141 for IACC and https://link.springer.com/chapter/10.1007/978-3-030-05710-7_29 for V3C (also as preprint https://arxiv.org/abs/1810.04401). V3C is also used for another retrieval campaign, the Video Browser Showdown (https://videobrowsershowdown.org), where IACC was also used in the past. Listing this stuff just under TRECVID is therefore not entirely accurate.

**Comment by xiaobai1217** [comment]
Thank you, fixed!
