### ISSUE TITLE
MSU Compressed Video Quality Assessment Dataset (CVQAD)

### ISSUE THREAD

**Issue by msm1rnov** [xiaobai1217/Awesome-Video-Datasets#12]
Hello! I'm impressed by your video datasets collection. Appreciate your work! Could you kindly add the MSU Compressed Video Quality Assessment Dataset (CVQAD)? Links to add: [Paper](https://videoprocessing.github.io/vc_dataset_vqm_benchmark) and [Homepage](https://videoprocessing.ai/datasets/vqa.html).

**Comment by xiaobai1217** [comment]
Thank you! The dataset has been added!
