### ISSUE TITLE
Fixing EPIC-KITCHENS details

### ISSUE THREAD

**Issue by dimadamen** [xiaobai1217/Awesome-Video-Datasets#2]
EPIC-KITCHENS has been extended in 2020. The new information (in multiple places in your page) should be:

EPIC-KITCHENS: Scaling Egocentric Vision: The EPIC-KITCHENS Dataset
[https://arxiv.org/abs/2006.13256][Homepage]
100 hours, 37 participants, 29M frames, 90K action segments, 700 variable length videos, 97 verb classes, 300 noun classes, 4053 action classes

Also EPIC-KITCHENS has a video retrieval benchmark and challenge. So it's not only for action recognition.

Thanks for your efforts

**Comment by xiaobai1217** [comment]
Thank you, Fixed!

**Comment by dimadamen** [comment]
Thanks for that. Sorry I mistyped it's 20M frames (not 29 my fault). Actually looking at your classification, EPIC-KITCHENS fits better under Video+Language (similar to YouCook2) than under retrieval.

Also for your info, EPIC-KITCHENS, similar to VGG-Sound offers Audio-visual information.

And regarding the paper reference, you can mention that this work was accepted at ECCV 2018 first and extended into TPAMI 2020, as you seem to have mentioned venues for the other datasets.

**Comment by xiaobai1217** [comment]
Fixed again!

**Comment by dimadamen** [comment]
Thanks
