### ISSUE TITLE
Movie - Condensed Movies Dataset 

### ISSUE THREAD

**Issue by Andrew-Brown1** [xiaobai1217/Awesome-Video-Datasets#3]
Hey, awesome repo!

Could I request that a dataset please be added in the "Movie" category

Condensed Movies: Story Based Retrieval with Contextual Embeddings (ACCV 2020)
paper: https://arxiv.org/pdf/2005.04208.pdf
Homepage: https://www.robots.ox.ac.uk/~vgg/research/condensed-movies/
33,976 captioned clips from 3,605 movies,  400K+ face-tracks, 8K+ labelled characters, 20K+ subtitles, densely pre-extracted features for each clip (RGB, Motion, Face, Subtitles, Scene)

**Comment by xiaobai1217** [comment]
Thank you, fixed!

**Comment by Andrew-Brown1** [comment]
thanks!
