### ISSUE TITLE
TRECVID video captioning dataset (TRECVID-VTT) and HLVU

### ISSUE THREAD

**Issue by trecvid** [xiaobai1217/Awesome-Video-Datasets#6]
Hello,

  Thanks for this awesome collection!, and also for adding some of the TRECVID datasets.
Our datasets are either fully available for download OR available after submitting a data agreement form before download.

1) Would you please add the VTT dataset: TRECVID-VTT
https://ir.nist.gov/tv_vtt_data/
Paper : https://arxiv.org/abs/2009.09984

2) Also recently we released a small annotated video understanding dataset (HLVU):
https://drive.google.com/drive/u/1/folders/1q1Ca0aFJrF9tB8hsw-mrI9d4tzy5wlPZ
Paper : https://dl.acm.org/doi/abs/10.1145/3372278.3390742

Thanks!
George

**Comment by xiaobai1217** [comment]
Thank you, added!
