### ISSUE TITLE
Hi, please add PoseC3D ("revisiting skeleton-based action recognition") skeleton datasets

### ISSUE THREAD

**Issue by kennymckormick** [xiaobai1217/Awesome-Video-Datasets#9]
This dataset includes state-of-the-art 2D pose estimation results for various datasets: including FineGYM, NTURGB+D, UCF101, and HMDB51, which are available at https://github.com/open-mmlab/mmaction2/tree/master/tools/data/skeleton.

**Comment by xiaobai1217** [comment]
Added!
